remote_theme: vaibhavvikas/jekyll-theme-minimalistic

title: "Software voor OOSDII"
description: "Installatie- en configuratiegids"

navigation:
  - name: Welkom
    link: /intellij-gids/
  - name: Installatie software
    link: /intellij-gids/jdk-21/jdk-21.html
    sublist:
      - name: JDK 21
        link: /intellij-gids/jdk-21/jdk-21.html
      - name: 7-zip
        link: /intellij-gids/7-zip/7-zip.html
      - name: Scene Builder
        link: /intellij-gids/scenebuilder-installatie/scenebuilder-installatie.html
      - name: IntelliJ IDEA
        link: /intellij-gids/intellij-installatie/intellij-installatie.html
  - name: Configuratie IntelliJ
    link: /intellij-gids/intellij-configuratie/intellij-inline-completion.html
    sublist:
      - name: Inline completion uitschakelen (verplicht)
        link: /intellij-gids/intellij-configuratie/intellij-inline-completion.html
      - name: De JavaFX-plugin (verplicht)
        link: /intellij-gids/intellij-configuratie/intellij-javafx-plugin.html
      - name: Weergave-opties in IntelliJ aanpassen
        link: /intellij-gids/intellij-configuratie/intellij-weergave-opties.html
      - name: Je workspace instellen
        link: /intellij-gids/intellij-configuratie/intellij-workspace.html
      - name: Standaardoptie voor openen van een project
        link: /intellij-gids/intellij-configuratie/intellij-project-openen.html
      - name: Scene Builder integreren
        link: /intellij-gids/intellij-configuratie/intellij-scenebuilder-integratie.html
      - name: Visual Paradigm integreren
        link: /intellij-gids/intellij-configuratie/intellij-vp-integratie.html
      - name: Licentie achteraf toevoegen
        link: /intellij-gids/intellij-configuratie/intellij-licentie-achteraf.html

  - name: Aan de slag met IntelliJ
    link: /intellij-gids/maven-project-maken-OOSDII/maven-project-maken-OOSDII.html
    sublist:
      - name: Een project maken (zonder JavaFX)
        link: /intellij-gids/maven-project-maken-OOSDII/maven-project-maken-OOSDII.html
      - name: Een JavaFX-project maken
        link: /intellij-gids/javafx/javafx.html
      - name: Een gedownload Maven-project importeren
        link: /intellij-gids/maven-project-openen-OOSDII/maven-project-openen-OOSDII.html
      - name: Dependencies toevoegen
        link: /intellij-gids/dependencies-toevoegen/dependencies-toevoegen.html
      - name: Runnen en debuggen
        link: /intellij-gids/runnen-en-debuggen/runnen-en-debuggen.html
      - name: Werken met Scene Builder
        link: /intellij-gids/scenebuilder/scenebuilder.html
      - name: Onmisbare sneltoetsen
        link: /intellij-gids/handige-sneltoetsen/handige-sneltoetsen.html
      - name: Nuttige links
        link: /intellij-gids/nuttige-links/nuttige-links.html
  - name: Een bestaand Eclipse-project of een src-map openen
    link: /intellij-gids/eclipse-project-openen/eclipse-project-openen.html

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
